name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy to EC2 on dev branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_NAME }}
          REMOTE_USER: ${{ secrets.USER_NAME }}
          TARGET: ${{ secrets.TARGET }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "----Hitttt-----"
            ls
            cd ./test-app
            git checkout dev
            git pull
            node -v
            yarn install
            yarn build
            rm -rf -f /var/www/html/test-app/dist
            echo "remove done"
            cp -R ../dist/ /var/www/html/test-app/
            echo "copy done"